/**
 * Secure Slug Generation for Share Links
 *
 * Generates cryptographically secure, non-sequential slugs
 * that are impossible to enumerate or guess.
 */

import { customAlphabet } from 'nanoid';

// Custom alphabet: only unambiguous characters
// Removed: 0, O, 1, I, l (can be confused)
const ALPHABET = '23456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz';

// Generate 24-character slug
// 58^24 = 2.8 × 10^42 combinations - impossible to enumerate
const nanoid = customAlphabet(ALPHABET, 24);

/**
 * Generate a secure, unique slug for share links
 *
 * @returns A 24-character URL-safe slug
 *
 * @example
 * generateSecureSlug() // 'A7bK9mP2qR4sT6uV8wX0yZ2'
 */
export function generateSecureSlug(): string {
  return nanoid();
}

/**
 * Validate a slug format
 *
 * @param slug - The slug to validate
 * @returns true if valid, false otherwise
 */
export function isValidSlug(slug: string): boolean {
  // Must be 24 characters, only allowed characters
  const slugRegex = /^[23456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz]{24}$/;
  return slugRegex.test(slug);
}

/**
 * Check if slug is likely generated by our system
 *
 * @param slug - The slug to check
 * @returns true if it matches our format
 */
export function isSystemSlug(slug: string): boolean {
  // Must be 24 chars, alphanumeric (no special chars)
  if (slug.length !== 24) return false;
  if (!/^[a-zA-Z0-9]+$/.test(slug)) return false;
  return true;
}

/**
 * Generate multiple slugs for testing/benchmarking
 *
 * @param count - Number of slugs to generate
 * @returns Array of unique slugs
 */
export function generateMultipleSlugs(count: number): string[] {
  const slugs: string[] = [];
  const seen = new Set<string>();

  while (slugs.length < count) {
    const slug = generateSecureSlug();
    if (!seen.has(slug)) {
      slugs.push(slug);
      seen.add(slug);
    }
  }

  return slugs;
}

/**
 * Benchmark slug generation performance
 *
 * @param count - Number of slugs to generate
 * @returns Time taken in milliseconds
 */
export function benchmarkSlugGeneration(count: number): number {
  const start = performance.now();
  generateMultipleSlugs(count);
  const end = performance.now();
  return end - start;
}

// ============================================================================
// EXPORTS
// ============================================================================

export default {
  generateSecureSlug,
  isValidSlug,
  isSystemSlug,
  generateMultipleSlugs,
  benchmarkSlugGeneration,
};
