/**
 * Interactive Optimization Viewer
 * Before/After split view with diff highlighting
 */

import React, { useState } from "react";
import { motion } from "framer-motion";
import { TMultiStrategyOptimizationResponse } from "@/schemas/optimization";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Copy,
  Check,
  Download,
  Share2,
  Maximize2,
  ArrowRight,
  Sparkles,
  TrendingUp,
} from "lucide-react";
import { toast } from "react-hot-toast";

interface InteractiveOptimizationViewerProps {
  result: TMultiStrategyOptimizationResponse;
  className?: string;
}

export const InteractiveOptimizationViewer: React.FC<
  InteractiveOptimizationViewerProps
> = ({ result, className = "" }) => {
  const [copiedBefore, setCopiedBefore] = useState(false);
  const [copiedAfter, setCopiedAfter] = useState(false);
  const [viewMode, setViewMode] = useState<"split" | "unified">("split");

  const handleCopy = async (text: string, isBefore: boolean) => {
    try {
      await navigator.clipboard.writeText(text);
      if (isBefore) {
        setCopiedBefore(true);
        setTimeout(() => setCopiedBefore(false), 2000);
      } else {
        setCopiedAfter(true);
        setTimeout(() => setCopiedAfter(false), 2000);
      }
      toast.success("Copied to clipboard!");
    } catch (error) {
      toast.error("Failed to copy");
    }
  };

  const handleDownload = () => {
    const content = `# Prompt Optimization Report

## Original Prompt
${result.original_prompt}

## Optimized Prompt
${result.final_optimized_prompt}

## Improvement Summary
- Overall Improvement: ${result.overall_improvement_percentage.toFixed(1)}%
- Confidence Score: ${(result.overall_confidence_score * 100).toFixed(1)}%
- Processing Time: ${result.processing_time_ms}ms

## Strategies Applied
${result.metadata.strategies_applied.map((s) => `- ${s}`).join("\n")}

## Recommendations
${result.recommendations.map((r) => `- ${r}`).join("\n")}

---
Generated by PromptTemple Optimization Engine
`;

    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `optimization-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("Report downloaded!");
  };

  // Calculate difference highlights
  const getWordDiff = (original: string, optimized: string) => {
    const originalWords = original.split(/\s+/);
    const optimizedWords = optimized.split(/\s+/);

    const added: string[] = [];
    const removed: string[] = [];

    optimizedWords.forEach((word) => {
      if (!originalWords.includes(word)) {
        added.push(word);
      }
    });

    originalWords.forEach((word) => {
      if (!optimizedWords.includes(word)) {
        removed.push(word);
      }
    });

    return { added, removed };
  };

  const diff = getWordDiff(result.original_prompt, result.final_optimized_prompt);

  return (
    <div className={`space-y-6 ${className}`}>
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold text-hieroglyph flex items-center">
            <Sparkles className="h-8 w-8 mr-3 text-primary" />
            Optimization Result
          </h2>
          <p className="text-muted-foreground mt-2">
            Your prompt has been enhanced using {result.metadata.strategies_applied.length}{" "}
            optimization strategies
          </p>
        </div>
        <div className="flex items-center space-x-2">
          <Button
            variant={viewMode === "split" ? "default" : "outline"}
            size="sm"
            onClick={() => setViewMode("split")}
          >
            Split View
          </Button>
          <Button
            variant={viewMode === "unified" ? "default" : "outline"}
            size="sm"
            onClick={() => setViewMode("unified")}
          >
            Unified
          </Button>
        </div>
      </div>

      {/* Stats Bar */}
      <Card className="temple-card pyramid-elevation bg-gradient-to-r from-green-50 to-blue-50 border-green-200">
        <div className="p-6">
          <div className="grid grid-cols-4 gap-6">
            <div className="text-center">
              <div className="flex items-center justify-center mb-2">
                <TrendingUp className="h-5 w-5 text-green-600 mr-2" />
                <p className="text-3xl font-bold text-green-600">
                  +{result.overall_improvement_percentage.toFixed(0)}%
                </p>
              </div>
              <p className="text-xs text-muted-foreground">Overall Improvement</p>
            </div>
            <div className="text-center">
              <p className="text-3xl font-bold text-blue-600 mb-2">
                {(result.overall_confidence_score * 100).toFixed(0)}%
              </p>
              <p className="text-xs text-muted-foreground">Confidence Score</p>
            </div>
            <div className="text-center">
              <p className="text-3xl font-bold text-purple-600 mb-2">
                {result.processing_time_ms}ms
              </p>
              <p className="text-xs text-muted-foreground">Processing Time</p>
            </div>
            <div className="text-center">
              <p className="text-3xl font-bold text-orange-600 mb-2">
                {result.metadata.strategies_applied.length}
              </p>
              <p className="text-xs text-muted-foreground">Strategies Applied</p>
            </div>
          </div>
        </div>
      </Card>

      {/* Split View */}
      {viewMode === "split" && (
        <div className="grid md:grid-cols-2 gap-6">
          {/* Before */}
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.3 }}
          >
            <Card className="temple-card h-full">
              <div className="p-6">
                <div className="flex items-center justify-between mb-4">
                  <div>
                    <h3 className="text-lg font-semibold text-hieroglyph">
                      Original Prompt
                    </h3>
                    <p className="text-xs text-muted-foreground mt-1">
                      {result.original_prompt.split(/\s+/).length} words
                    </p>
                  </div>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => handleCopy(result.original_prompt, true)}
                  >
                    {copiedBefore ? (
                      <Check className="h-4 w-4" />
                    ) : (
                      <Copy className="h-4 w-4" />
                    )}
                  </Button>
                </div>
                <div className="p-4 bg-red-50 rounded-lg border border-red-200 min-h-[200px]">
                  <p className="text-sm whitespace-pre-wrap leading-relaxed">
                    {result.original_prompt.split(" ").map((word, idx) => (
                      <span
                        key={idx}
                        className={
                          diff.removed.includes(word)
                            ? "bg-red-200 px-1 rounded"
                            : ""
                        }
                      >
                        {word}{" "}
                      </span>
                    ))}
                  </p>
                </div>
              </div>
            </Card>
          </motion.div>

          {/* After */}
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.3 }}
          >
            <Card className="temple-card h-full border-green-300">
              <div className="p-6">
                <div className="flex items-center justify-between mb-4">
                  <div>
                    <h3 className="text-lg font-semibold text-hieroglyph flex items-center">
                      Optimized Prompt
                      <Badge className="ml-2 bg-green-600">Enhanced</Badge>
                    </h3>
                    <p className="text-xs text-muted-foreground mt-1">
                      {result.final_optimized_prompt.split(/\s+/).length} words
                    </p>
                  </div>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => handleCopy(result.final_optimized_prompt, false)}
                  >
                    {copiedAfter ? (
                      <Check className="h-4 w-4" />
                    ) : (
                      <Copy className="h-4 w-4" />
                    )}
                  </Button>
                </div>
                <div className="p-4 bg-green-50 rounded-lg border border-green-200 min-h-[200px]">
                  <p className="text-sm whitespace-pre-wrap leading-relaxed">
                    {result.final_optimized_prompt.split(" ").map((word, idx) => (
                      <span
                        key={idx}
                        className={
                          diff.added.includes(word)
                            ? "bg-green-200 px-1 rounded font-medium"
                            : ""
                        }
                      >
                        {word}{" "}
                      </span>
                    ))}
                  </p>
                </div>
              </div>
            </Card>
          </motion.div>
        </div>
      )}

      {/* Unified View */}
      {viewMode === "unified" && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3 }}
        >
          <Card className="temple-card">
            <div className="p-6">
              <div className="space-y-4">
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <Badge variant="outline">Original</Badge>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => handleCopy(result.original_prompt, true)}
                    >
                      {copiedBefore ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                    </Button>
                  </div>
                  <div className="p-4 bg-secondary rounded-lg">
                    <p className="text-sm whitespace-pre-wrap text-muted-foreground">
                      {result.original_prompt}
                    </p>
                  </div>
                </div>

                <div className="flex justify-center">
                  <ArrowRight className="h-6 w-6 text-primary" />
                </div>

                <div>
                  <div className="flex items-center justify-between mb-2">
                    <Badge className="bg-green-600">Optimized</Badge>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => handleCopy(result.final_optimized_prompt, false)}
                    >
                      {copiedAfter ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                    </Button>
                  </div>
                  <div className="p-4 bg-green-50 rounded-lg border border-green-200">
                    <p className="text-sm whitespace-pre-wrap font-medium">
                      {result.final_optimized_prompt}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </Card>
        </motion.div>
      )}

      {/* Recommendations */}
      {result.recommendations.length > 0 && (
        <Card className="temple-card pyramid-elevation">
          <div className="p-6">
            <h3 className="text-lg font-semibold text-hieroglyph mb-4">
              💡 Recommendations
            </h3>
            <ul className="space-y-2">
              {result.recommendations.map((rec, idx) => (
                <li key={idx} className="flex items-start space-x-2">
                  <span className="text-primary mt-1">•</span>
                  <span className="text-sm text-foreground">{rec}</span>
                </li>
              ))}
            </ul>
          </div>
        </Card>
      )}

      {/* Actions */}
      <div className="flex items-center justify-end space-x-3">
        <Button variant="outline" onClick={handleDownload}>
          <Download className="h-4 w-4 mr-2" />
          Export Report
        </Button>
        <Button variant="outline">
          <Share2 className="h-4 w-4 mr-2" />
          Share
        </Button>
        <Button className="bg-primary">
          <Check className="h-4 w-4 mr-2" />
          Use Optimized Prompt
        </Button>
      </div>
    </div>
  );
};
